import { Player } from '../interfaces/player.interface';

export const PLAYERS: Player[] = [
	{
		uid: 'player1_6677',
		userName: 'Juan Pérez',
		nickname: 'El Goleador',
		email: 'juan.perez@example.com',
		profilePhotoUrl:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Fplayer_02.png?alt=media&token=b2701201-12ac-4539-a629-75c9456c3386',
		dateOfBirth: '1995-06-15 00:00:00',
		gender: 'Male',
		city: 'Bogotá',
		country: 'Colombia',
		createdSince: '2020-03-10 00:00:00',
		subscriptionLevel: 'Premium',
		isVerified: true,
		bio: 'Apasionado del fútbol y goleador nato.',
		followers: [
			'user_7693',
			'user_4456',
			'user_4343',
			'user_7585',
			'user_6502',
			'user_2723',
			'user_7224'
		],
		favorites: [],
		lastLogin: '2025-03-11 13:52:32.867412',
		status: 'Active',
		rolesList: ['PLAYER'],
		rp_Height: 1.78,
		rp_Weight: 75,
		rp_goalsScored: [
			{
				matchDay: '2024-03-22 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 3,
				rivalTeam: 'Águilas Doradas',
				goalsRivalTeam: 1,
				goals: 3
			},
			{
				matchDay: '2024-02-13 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 2,
				rivalTeam: 'Águilas Doradas',
				goalsRivalTeam: 3,
				goals: 1
			},
			{
				matchDay: '2024-01-16 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 4,
				rivalTeam: 'Tigres FC',
				goalsRivalTeam: 2,
				goals: 2
			},
			{
				matchDay: '2024-01-16 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 1,
				rivalTeam: 'Tigres FC',
				goalsRivalTeam: 2,
				goals: 1
			},
			{
				matchDay: '2024-02-12 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 3,
				rivalTeam: 'Tigres FC',
				goalsRivalTeam: 0,
				goals: 3
			},
			{
				matchDay: '2024-02-12 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 3,
				rivalTeam: 'Fuerza Amarilla',
				goalsRivalTeam: 0,
				goals: 1
			},
			{
				matchDay: '2024-02-11 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 5,
				rivalTeam: 'Tigres FC',
				goalsRivalTeam: 1,
				goals: 3
			},
			{
				matchDay: '2024-01-21 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 5,
				rivalTeam: 'Tigres FC',
				goalsRivalTeam: 2,
				goals: 3
			},
			{
				matchDay: '2024-03-11 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 3,
				rivalTeam: 'Águilas Doradas',
				goalsRivalTeam: 1,
				goals: 3
			},
			{
				matchDay: '2024-03-22 00:00:00',
				tournamentName: 'Copa Bogotá',
				uidTournament: 'tourn_2247',
				myTeam: 'Leones FC',
				goalsMyTeam: 2,
				rivalTeam: 'Fuerza Amarilla',
				goalsRivalTeam: 1,
				goals: 1
			}
		],
		rp_goalsCount: 10,
		rp_cardssScored: [
			{
				matchDay: '2024-03-02 00:00:00',
				tournamentName: 'Copa Cali',
				uidTournament: 'tourn_5088',
				myTeam: 'Defensores FC',
				rivalTeam: 'Lobos',
				cardType: 'Red'
			},
			{
				matchDay: '2024-03-03 00:00:00',
				tournamentName: 'Copa Cali',
				uidTournament: 'tourn_5088',
				myTeam: 'Defensores FC',
				rivalTeam: 'Aguilas Doradas',
				cardType: 'Yellow'
			}
		],
		rp_fairPlay: 9.8,
		rp_matchPlayed: [
			{
				matchDay: '2024-01-25 00:00:00',
				tournamentDay: 1,
				uidMatch: 'match_8448',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-22 00:00:00',
				tournamentDay: 2,
				uidMatch: 'match_1863',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-24 00:00:00',
				tournamentDay: 3,
				uidMatch: 'match_8598',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-25 00:00:00',
				tournamentDay: 4,
				uidMatch: 'match_6928',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-17 00:00:00',
				tournamentDay: 5,
				uidMatch: 'match_4156',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 3,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-25 00:00:00',
				tournamentDay: 6,
				uidMatch: 'match_8353',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-25 00:00:00',
				tournamentDay: 7,
				uidMatch: 'match_9978',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 1,
				result: 'DRAW',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-24 00:00:00',
				tournamentDay: 8,
				uidMatch: 'match_9492',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 3,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 3,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-14 00:00:00',
				tournamentDay: 9,
				uidMatch: 'match_3054',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-10 00:00:00',
				tournamentDay: 10,
				uidMatch: 'match_9919',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-11 00:00:00',
				tournamentDay: 11,
				uidMatch: 'match_4433',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-15 00:00:00',
				tournamentDay: 12,
				uidMatch: 'match_9706',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 3,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-23 00:00:00',
				tournamentDay: 13,
				uidMatch: 'match_4256',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-17 00:00:00',
				tournamentDay: 14,
				uidMatch: 'match_9711',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-14 00:00:00',
				tournamentDay: 15,
				uidMatch: 'match_7299',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 16,
				uidMatch: 'match_7905',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-20 00:00:00',
				tournamentDay: 17,
				uidMatch: 'match_6623',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-12 00:00:00',
				tournamentDay: 18,
				uidMatch: 'match_9344',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-23 00:00:00',
				tournamentDay: 19,
				uidMatch: 'match_3674',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-18 00:00:00',
				tournamentDay: 20,
				uidMatch: 'match_2609',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 1,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-10 00:00:00',
				tournamentDay: 21,
				uidMatch: 'match_7722',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-11 00:00:00',
				tournamentDay: 22,
				uidMatch: 'match_9235',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-17 00:00:00',
				tournamentDay: 23,
				uidMatch: 'match_1511',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-15 00:00:00',
				tournamentDay: 24,
				uidMatch: 'match_3686',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 0,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-14 00:00:00',
				tournamentDay: 25,
				uidMatch: 'match_6979',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 1,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-11 00:00:00',
				tournamentDay: 26,
				uidMatch: 'match_4872',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 27,
				uidMatch: 'match_9877',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-13 00:00:00',
				tournamentDay: 28,
				uidMatch: 'match_8933',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-21 00:00:00',
				tournamentDay: 29,
				uidMatch: 'match_7981',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 0,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-18 00:00:00',
				tournamentDay: 30,
				uidMatch: 'match_1095',
				uidTournament: 'tourn_1850',
				myTeam: 'Leones FC',
				myTeamGoals: 2,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			}
		],
		rp_matchPlayedCount: 30,
		rp_matchWonCount: 8,
		rp_matchDrawCount: 4,
		rp_matchLostCount: 18,
		rp_teamPlayed: [
			{
				teamName: 'Leones FC',
				uidTeam: 'team_2405',
				urlTeamShield:
					'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Fequipo-leones-dorados.png?alt=media&token=7084a3d6-b0b5-4cd3-a336-34fa31e7f015',
				yearPlayed: 2024,
				active: true
			}
		],
		rp_tournamentPlayed: [
			{
				tournamentName: 'Torneo Amateur',
				uidTournament: 'tourn_1850',
				urlTournamentShield:
					'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-amateur-2025.png?alt=media&token=aa5830cf-33f8-42fc-adb3-9eeb74968ece',
				startTournament: '2024-01-15 00:00:00',
				statusTournament: 'InProgress',
				position: 1
			}
		],
		rp_awardsPlayerWon: [
			{
				awardId: 'award_8785',
				awardType: 'Goleador del torneo',
				teamName: 'Leones FC',
				tournamentName: 'Copa Bogotá',
				awarDate: '2024-02-10 00:00:00'
			}
		],
		rp_positionPreference: 'FORWARD',
		rp_assistsCount: 10,
		rp_cleanSheets: 0,
		penaltiesTakenCount: 5,
		penaltiesScoredCount: 4,
		penaltiesFacedCount: 0,
		penaltiesSavedCount: 0,
		rp_playerOfTheMatchCount: 8,
		rp_efficiency: 87.5,
		rp_popularityScore: 950
	},
	{
		uid: 'player3_1844',
		userName: 'Miguel Ángel Rivas',
		nickname: 'El Muro',
		email: 'miguel.rivas@example.com',
		profilePhotoUrl:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Fplayer_03.png?alt=media&token=97d60807-1675-472f-a6dc-b9bae7edb065',
		dateOfBirth: '2000-04-25 00:00:00',
		gender: 'Male',
		city: 'Cali',
		country: 'Colombia',
		createdSince: '2019-08-14 00:00:00',
		subscriptionLevel: 'Premium',
		isVerified: true,
		bio: 'Arquero apasionado, atajando cada disparo.',
		followers: [
			'user_7138',
			'user_6783',
			'user_9713',
			'user_1664',
			'user_7267',
			'user_5006',
			'user_1827',
			'user_7538',
			'user_1996',
			'user_3966',
			'user_6412',
			'user_1590',
			'user_3064',
			'user_2890',
			'user_3960',
			'user_2709',
			'user_1377',
			'user_7029',
			'user_3374',
			'user_1503',
			'user_2727',
			'user_4526',
			'user_2036',
			'user_8515',
			'user_7652',
			'user_1648',
			'user_2338',
			'user_6068'
		],
		favorites: [],
		lastLogin: '2025-03-11 13:52:32.868514',
		status: 'Active',
		rolesList: ['PLAYER'],
		rp_Height: 1.85,
		rp_Weight: 80,
		rp_goalsScored: [],
		rp_goalsCount: 0,
		rp_cardssScored: [
			{
				matchDay: '2024-03-02 00:00:00',
				tournamentName: 'Copa Cali',
				uidTournament: 'tourn_5088',
				myTeam: 'Defensores FC',
				rivalTeam: 'Lobos',
				cardType: 'Red'
			},
			{
				matchDay: '2024-03-03 00:00:00',
				tournamentName: 'Copa Cali',
				uidTournament: 'tourn_5088',
				myTeam: 'Defensores FC',
				rivalTeam: 'Aguilas Doradas',
				cardType: 'Yellow'
			}
		],
		rp_fairPlay: 8.7,
		rp_matchPlayedCount: 40,
		rp_matchWonCount: 17,
		rp_matchDrawCount: 9,
		rp_matchLostCount: 14,
		rp_teamPlayed: [
			{
				teamName: 'Guerreros del Valle',
				uidTeam: 'team_7515',
				urlTeamShield:
					'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Fequipo-guerreros-valle.png?alt=media&token=8425752e-48e9-4ccd-a9be-9735e8d97dbd',
				yearPlayed: 2022,
				active: true
			}
		],
		rp_positionPreference: 'GOALKEEPER',
		rp_assistsCount: 0,
		rp_cleanSheets: 15,
		penaltiesTakenCount: 0,
		penaltiesScoredCount: 0,
		penaltiesFacedCount: 20,
		penaltiesSavedCount: 10,
		rp_playerOfTheMatchCount: 6,
		rp_efficiency: 90.1,
		rp_popularityScore: 850,
		rp_tournamentPlayed: [
			{
				tournamentName: 'Torneo Caribe',
				uidTournament: 'tourn_4142',
				urlTournamentShield:
					'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-caribe.png?alt=media&token=57412cd0-0133-43a8-aeaa-7fe26a6bac8a',
				startTournament: '2024-01-10 00:00:00',
				statusTournament: 'InProgress',
				position: 6
			}
		],
		rp_matchPlayed: [
			{
				matchDay: '2024-02-12 00:00:00',
				tournamentDay: 1,
				uidMatch: 'match_4692',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-19 00:00:00',
				tournamentDay: 2,
				uidMatch: 'match_5167',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-11 00:00:00',
				tournamentDay: 3,
				uidMatch: 'match_8597',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 3,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-13 00:00:00',
				tournamentDay: 4,
				uidMatch: 'match_6906',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 5,
				uidMatch: 'match_9242',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 6,
				uidMatch: 'match_5984',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-25 00:00:00',
				tournamentDay: 7,
				uidMatch: 'match_6049',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-14 00:00:00',
				tournamentDay: 8,
				uidMatch: 'match_9074',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-14 00:00:00',
				tournamentDay: 9,
				uidMatch: 'match_4616',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 2,
				result: 'WIN',
				myGoals: 3,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-23 00:00:00',
				tournamentDay: 10,
				uidMatch: 'match_4036',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-21 00:00:00',
				tournamentDay: 11,
				uidMatch: 'match_8271',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 12,
				uidMatch: 'match_7665',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-20 00:00:00',
				tournamentDay: 13,
				uidMatch: 'match_7668',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-17 00:00:00',
				tournamentDay: 14,
				uidMatch: 'match_7678',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-15 00:00:00',
				tournamentDay: 15,
				uidMatch: 'match_4569',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-17 00:00:00',
				tournamentDay: 16,
				uidMatch: 'match_9055',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-23 00:00:00',
				tournamentDay: 17,
				uidMatch: 'match_3039',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-17 00:00:00',
				tournamentDay: 18,
				uidMatch: 'match_4735',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-13 00:00:00',
				tournamentDay: 19,
				uidMatch: 'match_4734',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-16 00:00:00',
				tournamentDay: 20,
				uidMatch: 'match_6567',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-15 00:00:00',
				tournamentDay: 21,
				uidMatch: 'match_9412',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-23 00:00:00',
				tournamentDay: 22,
				uidMatch: 'match_4087',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-20 00:00:00',
				tournamentDay: 23,
				uidMatch: 'match_8183',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-12 00:00:00',
				tournamentDay: 24,
				uidMatch: 'match_9003',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 1,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-24 00:00:00',
				tournamentDay: 25,
				uidMatch: 'match_5213',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Titanes',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 1,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-13 00:00:00',
				tournamentDay: 26,
				uidMatch: 'match_1531',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 2,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-15 00:00:00',
				tournamentDay: 27,
				uidMatch: 'match_6971',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-18 00:00:00',
				tournamentDay: 28,
				uidMatch: 'match_2264',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Fuerza Amarilla',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 1,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-03-11 00:00:00',
				tournamentDay: 29,
				uidMatch: 'match_3356',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 1,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-23 00:00:00',
				tournamentDay: 30,
				uidMatch: 'match_9588',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 0,
				result: 'WIN',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-01-25 00:00:00',
				tournamentDay: 31,
				uidMatch: 'match_9796',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-11 00:00:00',
				tournamentDay: 32,
				uidMatch: 'match_7103',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-23 00:00:00',
				tournamentDay: 33,
				uidMatch: 'match_1501',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-03-19 00:00:00',
				tournamentDay: 34,
				uidMatch: 'match_5197',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 35,
				uidMatch: 'match_7617',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 3,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 1,
				result: 'WIN',
				myGoals: 2,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-17 00:00:00',
				tournamentDay: 36,
				uidMatch: 'match_5949',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 0,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-01-22 00:00:00',
				tournamentDay: 37,
				uidMatch: 'match_1823',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Leones Negros',
				rivalTeamGoals: 0,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-22 00:00:00',
				tournamentDay: 38,
				uidMatch: 'match_3380',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 2,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'DRAW',
				myGoals: 0,
				playerOfTheMatch: true,
				attendance: true
			},
			{
				matchDay: '2024-02-23 00:00:00',
				tournamentDay: 39,
				uidMatch: 'match_3443',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 0,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 3,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			},
			{
				matchDay: '2024-02-20 00:00:00',
				tournamentDay: 40,
				uidMatch: 'match_7010',
				uidTournament: 'tourn_4142',
				myTeam: 'Defensores FC',
				myTeamGoals: 1,
				rivalTeam: 'Águilas Doradas',
				rivalTeamGoals: 2,
				result: 'LOSS',
				myGoals: 0,
				playerOfTheMatch: false,
				attendance: true
			}
		]
	}
];
