import { Tournament } from '../interfaces/tournament.interface';

export const TOURNAMENTS: Tournament[] = [
	{
		tournamentName: 'Copa Amateur 2025',
		uidTournament: 'tournament_001',
		urlTournamentPhoto: '',
		urlTournamentShield:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-amateur-2025.png?alt=media&token=aa5830cf-33f8-42fc-adb3-9eeb74968ece',
		primaryColor: '#FF5733',
		secondaryColor: '#33C3FF',
		adminTournamentName: 'Carlos Gómez',
		adminTournamentUid: 'admin_001',
		country: 'Colombia',
		mainCity: 'Bogotá',
		latitude: 4.711,
		longitude: -74.072,
		statusTournament: 'En Inscripción',
		startTournament: '2025-03-10',
		teams: 16,
		totalMatches: 32,
		totalGoals: 89,
		totalYellows: 12,
		totalReds: 3,
		totalTeams: 16,
		totalFollowers: 1050,
		popularityScore: 98,
		gender: 'masculino',
		minAge: 15,
		maxAge: 19,
		fields: ['Cancha Marte', 'cancha oriental', 'cancha sur'],
		formatSoccer: 'Futbol 11'
	},
	{
		tournamentName: 'Liga Futbol 8',
		uidTournament: 'tournament_002',
		urlTournamentPhoto: '',
		urlTournamentShield:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-liga-futbol8.png?alt=media&token=8a085172-442b-47af-b4f9-d385f00a23d4',
		primaryColor: '#FFC300',
		secondaryColor: '#DAF7A6',
		adminTournamentName: 'Andrea López',
		adminTournamentUid: 'admin_002',
		country: 'Colombia',
		mainCity: 'Medellín',
		latitude: 6.2442,
		longitude: -75.5812,
		statusTournament: 'En Curso',
		startTournament: '2025-04-05',
		teams: 12,
		totalMatches: 24,
		totalGoals: 72,
		totalYellows: 8,
		totalReds: 2,
		totalTeams: 12,
		totalFollowers: 890,
		popularityScore: 85,
		gender: 'Femenino',
		minAge: 21,
		maxAge: 30,
		fields: ['Cancha Bolívar', 'Cancha Santander'],
		formatSoccer: 'Futbol 8'
	},
	{
		tournamentName: 'Torneo Juvenil Sub-17',
		uidTournament: 'tournament_003',
		urlTournamentPhoto: '',
		urlTournamentShield:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-juvenil-sub17.png?alt=media&token=29c0976d-8fc1-4d79-bdf6-41e0f0272c63',
		primaryColor: '#4CAF50',
		secondaryColor: '#FFC107',
		adminTournamentName: 'Juan Pérez',
		adminTournamentUid: 'admin_003',
		country: 'Colombia',
		mainCity: 'Cali',
		latitude: 3.4516,
		longitude: -76.532,
		statusTournament: 'Finalizado',
		startTournament: '2024-12-20',
		teams: 20,
		totalMatches: 40,
		totalGoals: 120,
		totalYellows: 20,
		totalReds: 5,
		totalTeams: 20,
		totalFollowers: 750,
		popularityScore: 82,
		minAge: 15,
		maxAge: 17,
		fields: ['Cancha del Bosque'],
		formatSoccer: 'Futbol 5'
	},
	{
		tournamentName: 'Copa del Caribe',
		uidTournament: 'tournament_004',
		urlTournamentPhoto: '',
		urlTournamentShield:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-caribe.png?alt=media&token=57412cd0-0133-43a8-aeaa-7fe26a6bac8a',
		primaryColor: '#0074D9',
		secondaryColor: '#FF851B',
		adminTournamentName: 'Luis Martínez',
		adminTournamentUid: 'admin_004',
		country: 'Colombia',
		mainCity: 'Cartagena',
		latitude: 10.391,
		longitude: -75.4794,
		statusTournament: 'En Curso',
		startTournament: '2025-02-01',
		teams: 10,
		totalMatches: 20,
		totalGoals: 60,
		totalYellows: 5,
		totalReds: 1,
		totalTeams: 10,
		totalFollowers: 670,
		popularityScore: 78,
		minAge: 25,
		maxAge: 40,
		fields: ['Cancha Mutis', 'Cancha El Bueno'],
		formatSoccer: 'Futbol 7'
	},
	{
		tournamentName: 'Fútbol Master Senior',
		uidTournament: 'tournament_005',
		urlTournamentPhoto: '',
		urlTournamentShield:
			'https://firebasestorage.googleapis.com/v0/b/gatoz-v04-1.appspot.com/o/public-folder%2Ftorneo-senior.png?alt=media&token=c3c8c361-78c6-4c4c-9069-ec22081a8c46',
		primaryColor: '#800080',
		secondaryColor: '#FFD700',
		adminTournamentName: 'Felipe Ríos',
		adminTournamentUid: 'admin_005',
		country: 'Colombia',
		mainCity: 'Barranquilla',
		latitude: 10.9639,
		longitude: -74.7964,
		statusTournament: 'En Inscripción',
		startTournament: '2025-05-15',
		teams: 14,
		totalMatches: 28,
		totalGoals: 78,
		totalYellows: 10,
		totalReds: 2,
		totalTeams: 14,
		totalFollowers: 630,
		popularityScore: 75,
		minAge: 41,
		maxAge: 55,
		fields: ['Cancha Mutis', 'Cancha El Bueno'],
		formatSoccer: 'Futbol 11'
	}
];
